### ISSUE TITLE
Link from bios to OLS projects people participated to

### ISSUE THREAD

**Issue by bebatut** [open-life-science/open-life-science.github.io#418] opened 2022-09-16 14:53 UTC
Suggested by a community member:

"When I go in projects and participants of previous OLSs, like OLS5, I can click on the project leads of each project (https://openlifesci.org/ols-5/projects-participants/), and that takes me to their bios. It'd be nice that if I am in the bios, I can see which project XY person is related to."

**Comment by NPDebs** [comment] 2022-10-09 03:22
Hi @bebatut 👋🏼🙂
I'm an Outreachy intern and would absolutely love to work on this issue. Thanks!

**Comment by Jolah1** [comment] 2022-10-10 12:01
Hello @bebatut 
My name is Jolade, I am an Outreachy applicant, I will be working on this issue.
thank you.

**Comment by bebatut** [comment] 2022-10-10 12:10
As defined in the [OLS Outreachy contribution guide](https://docs.google.com/document/d/1HP7qTBe-6YrCUYAVkrT441rGtF6zxzNbbz2E5RWQvTM/edit?usp=sharing), 
- If someone else has already commented, let them try first
- If they don’t update after three days, the issue is “free” again, and you can pick it up. 

@NPDebs were the first one to comment here. Are you still interested to work on this issue? You are already interested in other issues. You might need to pick one

**Comment by NPDebs** [comment] 2022-10-10 15:06
> As defined in the [OLS Outreachy contribution guide](https://docs.google.com/document/d/1HP7qTBe-6YrCUYAVkrT441rGtF6zxzNbbz2E5RWQvTM/edit?usp=sharing), 
> - If someone else has already commented, let them try first
> - If they don’t update after three days, the issue is “free” again, and you can pick it up. 
> 
> @NPDebs were the first one to comment here. Are you still interested to work on this issue? You are already interested in other issues. You might need to pick one

Hi @bebatut 
Yeah. I was throwing darts, hoping to land as many contributions as possible! 😅

I'll take whatever you assign to me. Thank you!

**Comment by NPDebs** [comment] 2022-10-11 11:23
> You are already assigned to another one. Finish it and if this issue is still not assigned you could work on it later

Alrightie. Thank you! @bebatut

**Comment by NPDebs** [comment] 2022-10-13 03:52
> You are already assigned to another one. Finish it and if this issue is still not assigned you could work on it later

Hi @bebatut. 😃

I'm now free as a bird! Well, technically, my PRs are yet to be reviewed and merged. 😅

Can I please start working on this one while I wait? Please, please, pretty please! 🙏🏼

**Comment by bebatut** [comment] 2022-10-13 07:14
Ok. I assign it to you @NPDebs

**Comment by NPDebs** [comment] 2022-10-13 07:34
Thank you, @bebatut ! 🙌🏼🥰

Just to be verify my understanding of the issue, I have a few questions, please.


This is a project called "ABC..." **Vicky Hellon** is a participant.

![Screenshot_20221013-082844_Chrome.jpg](https://user-images.githubusercontent.com/105166953/195530911-02d19faf-6732-4d98-b016-f568d8c69aef.jpg)

When I click on her name, it goes to her bio. The goal of this issue is to add a section that states what projects she's involved in, right?

![Screenshot_20221013-082912_Chrome.jpg](https://user-images.githubusercontent.com/105166953/195531580-124f0201-a46a-4968-a8c2-22da62c22252.jpg)

**Comment by bebatut** [comment] 2022-10-13 07:37
Yes that is the idea.
If you look also at the people page, you can see the role of people in the different cohorts. It could be nice when they were participants to add also there the link to their project in the cohort they participated to

**Comment by NPDebs** [comment] 2022-10-13 07:52
Okay. 👌🏼 I understand the first part of the task.

When I got to the [people page](https://openlifesci.org/people), this is what I find...
![Screenshot_20221013-085059_Chrome.jpg](https://user-images.githubusercontent.com/105166953/195535771-e15de778-f6f3-4d0f-a670-a66fe7e5cb34.jpg)

**Comment by bebatut** [comment] 2022-10-13 08:01
below you see more details about the people

**Comment by NPDebs** [comment] 2022-10-13 08:11
> below you see more details about the people

Ah. Yes yes! Seen. 

I'll get right on it, and revert to you if I have some more questions. Thanks for your patience. 🙏🏼

**Comment by NPDebs** [comment] 2022-10-15 19:05
Hi @bebatut. 👋 
Here's a little progress update from me to you...

In the _people.yaml_ file, I added a new `key`, named `projects` and assigned its `value` to be the name of the project the individual participated in. (Note: This info was gotten from the _projects.yaml_ file of each cohort)

Additionally, I specified the `cohort` of the individual as a new key.

In lines 74-79 of the `people.html` file (under `_includes`), you will find the block of code I used to reference these new keys, and print them on the "bio card" of each participant.

On click, the link goes to `"https://openlifesci.org/{{% user.cohort %}}/projects-participants/"`.

![ols-progress-update](https://user-images.githubusercontent.com/105166953/196002853-2f09f709-190d-4df9-bb32-ba4f18a0013c.png)

I have only done this for the members of cohort ols-1. Please, kindly let me know if I am on the right track, so that I can do the same for the remaining cohorts.

I have attached a link to the commit containing the aforementioned changes, right [HERE](https://github.com/open-life-science/open-life-science.github.io/commit/6d0f28370694c6a7730040c413d4de35e2d7e745).


**Thank you for your time.**
Best regards.

**Comment by bebatut** [comment] 2022-10-17 08:41
Thanks @NPDebs for the initial work there.

Regarding adding project information in the  `people.yaml` file
- I try to avoid adding several time the same information in different location: it gets easily unsynchronized. The information about in which project people are involved is already available in the `ols-x-projects.yaml` files
- The `people.yaml` should also only keep information about the people, not their participation in OLS

In the `people.html` file, you can see [starting on line 41](https://github.com/open-life-science/open-life-science.github.io/blob/main/_layouts/people.html#L41) that I already extract information about roles of people in the different OLS cohorts.
You could add there the extraction of the name of project in which they participated.

Btw, I realize the information about participation in OLS cohorts is not displayed anymore in the card as it used to be inside the  "Role in OLS: " blurb
That would be nice to fix that, and then for participants, adding there the link to their project as `{{ site.ur }}/{{ cohort }}/projects-participants/{{ project }}` (adding then also the link to the project section in the page, a bit like done in the table on the bottom the project page)

**Comment by NPDebs** [comment] 2022-10-18 21:50
Hi @bebatut. 👋 

Progress update: Not so much progress.
I successfully extracted the **projects** in each cohort by looping through `ols-1-projects.yaml`.

```
    {% for proj in project.name %}
        {% capture ols-1-projectnames %}{{ ols-1-projectnames }} {{ proj }}{% endcapture %}
    {% endfor %}
```
I rendered that on a page to confirmed that it worked. See **screenshot** below:

![Screenshot (298)](https://user-images.githubusercontent.com/105166953/196537503-9a7be948-f123-4501-9db4-dc6c5506afb1.png)

To render the specific project a person is associated with (on their bio card), I wrote this block of code. 👇 

```
    {% for person in ols-1-participants &}
        {% for project in ols-1-projects %}
            {% if project contains person %}
                {% capture project-name %}{{ project-name }}{{ project.name }}{% endcapture %}
            {% endif %}
        {% endfor %}
    {% endfor %}
```

**Explanation:** 
The variable _ols-1-participants_ stores all the participants, and _ols-1-projectnames_ contains all the projects.

So, I attempted to loop through each person. For that person, loop through the _projects_, checking for the person in the project.

Since `project` here represents a unique project (with name, participants, mentors and description), the condition ought to check if the **person** is in the project. If this condition is met, then _capture_ the `name` of the project (i.e project.name of the project containing the participant, **person**).

A link to my commits are attached [here...](https://github.com/open-life-science/open-life-science.github.io/compare/main...NPDebs:open-life-science.github.io:Fix418).

Please tell me know your thoughts on this. Thank you for your patience! 🤝

**Comment by NPDebs** [comment] 2022-10-19 14:52
Hi @bebatut. I'm glad you approve of my approach, however fruitless it may seem at the moment. 😂

What's displayed on the card is actually the name, and not the description of the projects. That particular project seemed to have a really long title. 😃


About the linked commit.......I removed the block of code that threw an error.
Would you like me to put that back in and push?

**Comment by NPDebs** [comment] 2022-10-19 15:31
> Up to you right now 😄 
> How can I help you on that?

Well, for one...I'd like to know how I can relate all the keys in a particular project to each other.

If the participant is in the same place as the "name" of the project, then render the name of the project.

It seems so straightforward. Yet, the logic has been flying over my head for days.

**Comment by bebatut** [comment] 2022-10-19 15:57
I think I am not sure to follow / understand here

**Comment by NPDebs** [comment] 2022-10-19 16:19
> I think I am not sure to follow / understand here

Okay. Here's my train of thought.

Loop through the participants. Within that loop, begin to loop through the project.yaml file.

 For each participant, check if the person's is the same as `project.participants`. Then capture the name of that project (where person == participant name), and render it on the card.

Does that make much sense?

If it's not too much to ask, can we do a quick Slack call at your convenience, please? @bebatut

**Comment by bebatut** [comment] 2022-10-20 06:58
The loop over the `project.yaml` file are already done before in the page to get if people participated in cohorts.
You could use that loop to extract projects for each cohort.

Then when looping on the people to create the card, you could check their status (in which cohort they participated) and for the cohort in which they were participants, looping on the projects for that cohort to extract the project name

Do you understand what I mean? I am not sure if my way of explaining is clear :smile:

**Comment by NPDebs** [comment] 2022-10-20 07:46
Hi @bebatut.
Thank you for your response. Yes, I was actually following your explanation, until my brain got stuck in all the loops. 😄 

When you say a loop has already been done, do you mean from line 41?

Yesterday, I was looking at how you wrote the logic for a similar thing, [here](https://github.com/open-life-science/open-life-science.github.io/edit/main/_ols-1/projects-participants.md). It gave me an idea, but I still did not succeed.

Maybe we can communicate better over a call?

**Comment by bebatut** [comment] 2022-10-21 07:23
> When you say a loop has already been done, do you mean from line 41?

Yes

> This is what I did...

I think I do not understand your logic there. Participants are extracted from the `ols-1-projects` (in loop starting in line 41) so it is better to use the previous loop .
And also if you loop there, you are not yet in the big loop on the people so the project name will not be rendered.

Try to implement my suggestions from yesterday

**Comment by NPDebs** [comment] 2022-10-21 11:04
Hi @bebatut.
Yesterday, after brainstorming with a fellow Outreachy participant, we were able to output the title of one participant's project on her card.
But the twist is, it also got printed on all the participants for OLS-1. 😅 A problem in the loop, apparently. 


Thank you for your suggestions. I'll try to implement them as soon as I resolve the Gitpod/Miniconda situation.

Yes, I'll be joining the call, later today. I'll ask them any questions I might have and update you.

Thank you. 🙌🏼

**Comment by NPDebs** [comment] 2022-10-24 08:47
Hi @bebatut.

For the **Roles in OLS:** part...it shows up for only the organisers of OLS. This is because only organisers have it as a `key:value` pair, under **title**. Shouldn't the other people also have titles, to be displayed as roles on their cards?

![Screenshot_20221024-090424_Chrome~2](https://user-images.githubusercontent.com/105166953/197485771-22fb73eb-3258-4ed3-9492-084ac7a52522.jpg)
![Screenshot_20221024-093419_Chrome~2](https://user-images.githubusercontent.com/105166953/197485780-00c59a68-46c7-4ca9-917a-34092dba7935.jpg)

**Comment by bebatut** [comment] 2022-10-24 09:13
The role of participants (participant, mentor, etc in the different cohorts) are extracted here: https://github.com/open-life-science/open-life-science.github.io/blob/main/_layouts/people.html
It should be displayed, given the code here: https://github.com/open-life-science/open-life-science.github.io/blob/main/_includes/people.html#L59
I did not investigate why it is not the case anymore

**Comment by NPDebs** [comment] 2022-10-25 22:41
Hi @bebatut. 👋

I tweaked the logic a bit and the cards now display the people's **roles**.
Here's a [link](https://github.com/open-life-science/open-life-science.github.io/compare/main...NPDebs:open-life-science.github.io:FixRoles) to the commit.

![Screenshot (330)](https://user-images.githubusercontent.com/105166953/197894659-97d89827-466a-44af-a0d1-106daf10c93f.png)

**Observation:**
- Onclick, the 'card-toggle' icon does not do anything. Is this to be expected?

**Two quick questions, please:**

1.  Would you like me to make the _**Roles in OLS:**_ bold too?
2. Can I open a PR for this fix?

Thank you! 🙌

**Comment by bebatut** [comment] 2022-10-26 07:39
Please open the PR with the fix.
For making `Roles in OLS:` bold, not sure. Because `Expertise` is not bold

**Comment by NPDebs** [comment] 2022-10-26 07:48
> Please open the PR with the fix :smile: 
> For making `Roles in OLS:` bold, not sure. Because `Expertise` is not bold

Thank you! I'll open the PR right away. 😃

Oh, that's true. We either make both bold...or maintain the current state.

**Comment by yochannah** [comment] 2024-07-23 16:15
solved by https://github.com/open-life-science/open-life-science.github.io/pull/496

**Closed by yochannah** 2024-07-23 16:15 UTC
Labels: hacktoberfest, advanced
