### ISSUE TITLE
Key personnel avatar and Github link not working properly

### ISSUE THREAD

**Issue by looonnng** [open-life-science/open-life-science.github.io#781] opened 2024-05-13 20:23 UTC
Hi, on the Research on Open page, the Github links take you to the Github homepage instead of the personnel profile
And, the personnel avatar is not displaying like below:

![image](https://github.com/open-life-science/open-life-science.github.io/assets/122837733/cf455af6-d2bb-4ae8-82a3-6a306fa88769)

**Comment by NPDebs** [comment] 2024-05-24 20:59
Hi, @looonnng. 👋 
Thank you so much for flagging such an important issue!

Your feedback helped us discover this in a few other pages as well. I think this is caused by buggy code, where we used a variable without declaring it first. :-) We'll get this up and running in no time.

Thanks again!

**Comment by bebatut** [comment] 2024-05-25 13:38
Fixed with #785

**Closed by bebatut** 2024-05-25 13:38 UTC
