### ISSUE TITLE
Add page to collect testimonies about the program 

### ISSUE THREAD

**Issue by bebatut** [open-life-science/open-life-science.github.io#200] opened 2020-09-28 15:40 UTC
We have some testimonies about the impact of OLS on people, e.g. https://twitter.com/_lacion_/status/1310290749536137216. 
It would be nice to have some available on the website.

**Comment by Lovelyfin00** [comment] 2022-10-10 05:46
Hi @bebatut
Is this issue still up for grabs?
I would love to be assigned to it
And can more explanation on whatvis needed be given?

**Comment by bebatut** [comment] 2022-10-10 13:07
I updated the description @Lovelyfin00. I hope it is a bit more clear

**Comment by tnwoodard** [comment] 2022-10-10 14:14
Hi @bebatut. Thank you for coordinating this. Is this issue free for me to work or was it chosen already? If chosen, will you please add me to the queue if it is not resolved soon?  Thank you! 👍🏾

**Comment by Lovelyfin00** [comment] 2022-10-10 15:50
@bebatut 
Yes
It's clear now
So which of the pages is it supposed to be added to?

**Comment by bebatut** [comment] 2022-10-11 08:01
@Lovelyfin00 do you want to be assigned to this issue?

**Comment by bebatut** [comment] 2022-10-11 09:34
Please look at the documentation of [Jekyll](https://jekyllrb.com/) to understand how it works

**Comment by IdayatSanni** [comment] 2022-10-11 19:38
Hello, can I be assigned this task?

**Comment by IdayatSanni** [comment] 2022-10-11 19:41
Hi @bebatut, I don't know if this has been assigned. Can I work on this?

**Comment by yochannah** [comment] 2024-06-25 15:22
duplicate of #708

**Closed by yochannah** 2024-06-25 15:22 UTC
Labels: hacktoberfest, advanced
